server:
    port: 8090
spring:
    data:
        mongodb:
            host: localhost
            port: 29019
            database: test
    logging:
        file: expenses.log
        level:
           root=WARN
           org.springframework.web