server:
    port: 8090
spring:
    data:
        mongodb:
            host: 192.168.99.100
            port: 27017
            database: test
    logging:
        file: expenses.log
        level:
           root=WARN
           org.springframework.web