spring:
    profiles:
        active: prod
    application:
        name: expenses
jwt:
    sharedSecretKey: $Sh4r3dUk49kzmpo98i7h4xv21md
    subject: expenses
    issuer: https://expenses.com
    tokenDuration: 600000

   
