server:
    port: 8090
spring:
    data:
        mongodb:
            host: mongodb
            port: 27017
            database: test
    logging:
        file: expenses.log
        level:
           root=WARN
           org.springframework.web